### ISSUE TITLE
kmd run without data directory results in stack dump

### ISSUE THREAD

**Issue by purestaketdb** [algorand/go-algorand-doc#10]
Poking around at new kmd function, ran on command line without any parameters, results in stack dump - desired outcome is standard help error 

ERRO[0000] [Stack] goroutine 1 [running]:
runtime/debug.Stack(0xc0001ee640, 0xc00000e0a0, 0xc0001ee6e0)
	/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/runtime/debug/stack.go:24 +0xa7
github.com/algorand/go-algorand/logging.logger.Errorf(0xc0001ee640, 0xc00000e0a0, 0xde2849, 0x23, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/algorand/go-algorand/logging/log.go:223 +0x4b
main.main()
	/home/travis/gopath/src/github.com/algorand/go-algorand/cmd/kmd/main.go:32 +0x70c
  file=main.go function=main.main line=32
ERRO[0000] dataDir (-d) is a required argument           file=main.go function=main.main line=32

**Comment by Karmastic** [comment]
Fixed
